server:
  port: 8762
spring:
  application:
    name: service-hi
  rabbitmq:       #通过rabbitmq的方式将服务链路的数据发送给server-zipkin 同时去掉原先配置中的server-zipkin地址
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    web:
      client:
        enabled: true #web开启sleuth功能
    sampler:
      percentage: 1.0 #表示采样比例，最大为1.0即就是链路数据100%收集到server-zipkin
  #zipkin:
  #  base-url: http://localhost:9411/ #指定server-zipkin的服务地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

