spring:
  application:
    name: admin-client
  #boot:
  #  admin:
  #    client:
  #      url: http://localhost:8769 #配置为springcloud-admin的server端地址
server:
  port: 8768

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*' #暴露自己的actuator的所有端口信息
  endpoint:
    health:
      show-details: always